name: covid tracking project

on: 
#    schedule:
   #run daily at 5:20 UTC
#      - cron: '20 5 * * *'

  # push:
   watch: [ master ]

jobs:
 covid-tracking-state:   
    name: CTP-State Data Ingestion
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
       #set up username and id 
    - uses: fregante/setup-git-token@v1
      with:
         token: ${{ secrets.GITHUB_TOKEN }}
    - name: pull data via curl
      run: |
       git remote add github "https://$GITHUB_ACTOR:$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY.git"
       git pull github ${GITHUB_REF} --ff-only
       /bin/sh scripts/csvDownload.sh COVID_TRACKING_STATE_HIST https://api.covidtracking.com/v1/states/daily.csv data/us/covidtracking/state/raw
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
         pip install pandas
         pip install addfips
    - name: transform
      run: |
       python data/us/covidtracking/state/harvester.py
       git add .
       git commit -m "adding CTP data via github actions"
       git push github HEAD:${GITHUB_REF}
    - name: Slack notification
      #should run if any previous step fails
      if: failure()
      env:
       SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
       SLACK_USERNAME: GitHub Actions # Optional. (defaults to webhook app)
       SLACK_CHANNEL: alerts-rds # Optional. (defaults to webhook)
       SLACK_AVATAR: repository # Optional. can be (repository, sender, an URL) (defaults to webhook app avatar)
      uses: Ilshidur/action-slack@master
      with:
          args: 'Something went wrong in the Covid Tracking State workflow.' # Optional

