name: run JH scripts

on: 
  schedule:
  #run every night at midnight
    - cron: '0 0 * * *'
# on:
#   push:
#    #run on every push to master
#     branches: [ master ]

jobs:
  linux:
    name: Pull yesterday's JH data
    runs-on: ubuntu-latest
    
    steps:
      #checkout branch to work on it 
    - uses: actions/checkout@v2
       #set up username and id 
    - uses: fregante/setup-git-token@v1
      with:
         token: ${{ secrets.GITHUB_TOKEN }}
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
    - name: Pull and commit data
      run: |
       pip install pandas
       cd data/us/jhu-ccse
       python harvester.py -c
       git remote add github "https://$GITHUB_ACTOR:$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY.git"
       git pull github ${GITHUB_REF} --ff-only
       git add .
       git commit -m "added daily Johns Hopkins data via pipeline"
       git push github HEAD:${GITHUB_REF}
