name: Johns Hopkins Data Ingestion/Transformation

on: 
  schedule:
  #run every night at 1am Eastern Time, since JH is updated around midnight ET.
  #Github actions use UTC time which is 4 hours ahead of ET.
   - cron: '0 5 * * *'

# uncomment these lines if you need to run the pipeline manually. 
#   push:
#    #run on every push to master
#     branches: [ master ]

jobs:
  jh:
    name: JH data ingestion/transformation
    runs-on: ubuntu-latest
    
    steps:
      #checkout branch to work on it 
    - uses: actions/checkout@v2
    - name: Setup git user
      run: |
         git config --global user.name "$(git --no-pager log --format=format:'%an' -n 1)"
         git config --global user.email "$(git --no-pager log --format=format:'%ae' -n 1)"
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
    - name: Pull and commit data
      run: |
       pip install pandas
       cd data/us/jhu-ccse
       python harvester.py -c
       git remote add github "https://$GITHUB_ACTOR:$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY.git"
       git pull github ${GITHUB_REF} --ff-only
       git add .
       git commit -m "added daily Johns Hopkins data via pipeline"
       git push github HEAD:${GITHUB_REF}

  covid-tracking-state:   
    name: CTP-State Data Ingestion
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
       #set up username and id 
    - uses: fregante/setup-git-token@v1
      with:
         token: ${{ secrets.GITHUB_TOKEN }}
    - name: pull data via curl
      run: /bin/sh scripts/csvDownload.sh COVID_TRACKING_STATE_HIST https://covidtracking.com/api/v1/states/daily.csv data/us/covidtracking/state/raw
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
         pip install pandas
         pip install addfips
    - name: transform
      run: |
       #git remote add github "https://$GITHUB_ACTOR:$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY.git"
       git pull github ${GITHUB_REF} --ff-only
       python data/us/covidtracking/state/harvester.py
       git add .
       git commit -m "adding CTP data via github actions"
       git push github HEAD:${GITHUB_REF}
       
  ca-gov:
   name: CA-GOV Data Ingestion
   runs-on: ubuntu-latest
   steps:
    - uses: actions/checkout@v2
       #set up username and id 
    - uses: fregante/setup-git-token@v1
      with:
         token: ${{ secrets.GITHUB_TOKEN }}
    - name: pull data via curl
      run: /bin/sh scripts/csvDownload.sh CA_GOV https://health-infobase.canada.ca/src/data/covidLive/covid19.csv data/ca/gov/raw
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
         pip install pandas
    - name: transform
      run: |
       #git remote add github "https://$GITHUB_ACTOR:$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY.git"
       git pull github ${GITHUB_REF} --ff-only
       python data/ca/gov/harvester.py
       git add .
       git commit -m "adding CA-GOV data via github actions"
       git push github HEAD:${GITHUB_REF}
       
  ca-statcan:
   name: StatsCan Data Ingestion
   runs-on: ubuntu-latest
   steps:
    - uses: actions/checkout@v2
       #set up username and id 
    - uses: fregante/setup-git-token@v1
      with:
         token: ${{ secrets.GITHUB_TOKEN }}
    - name: pull data via curl
      run: /bin/sh scripts/statCanDownload.sh https://www150.statcan.gc.ca/n1/tbl/csv/13100766-eng.zip 13100766.csv data/ca/statcan/raw/
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
         pip install pandas
    - name: transform
      run: |
       git remote add github "https://$GITHUB_ACTOR:$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY.git"
       git pull github ${GITHUB_REF} --ff-only
       python data/ca/statcan/harvester.py
       git add .
       git commit -m "adding StatsCan data via github actions"
       git push github HEAD:${GITHUB_REF}
       
       
       
   
       
  
