name: NY DOH Data

on: 
   schedule:
   #run daily at 5:40 UTC
     - cron: '40 5 * * *'
# on:
#  push:
#    branches: [ master ]

jobs:
 ny-doh:   
    name: NY-DOH Data Ingestion
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
       #set up username and id 
    - uses: fregante/setup-git-token@v1
      with:
         token: ${{ secrets.GITHUB_TOKEN }}
    - name: pull data via curl
      run: /bin/sh scripts/csvDownload.sh NY https://health.data.ny.gov/api/views/xdss-u53e/rows.csv?accessType=DOWNLOAD data/us-ny/ny-doh/raw
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
         pip install pandas
         pip install addfips
    - name: transform
      run: |
       git remote add github "https://$GITHUB_ACTOR:$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY.git"
       git pull github ${GITHUB_REF} --ff-only
       python data/us-ny/ny-doh/harvester.py
       git add .
       git commit -m "adding NY data via github actions"
       git push github HEAD:${GITHUB_REF}
