name: OH DOH Data

on: 
#    schedule:
   #run daily at 5:30 UTC
#      - cron: '30 5 * * *'
  push:
   branches: [ master ]

jobs:
 oh-doh:   
    name: OH-DOH Data Ingestion
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
       #set up username and id 
    - uses: fregante/setup-git-token@v1
      with:
         token: ${{ secrets.GITHUB_TOKEN }}
    - name: pull data via curl
      run: |
          git remote add github "https://$GITHUB_ACTOR:$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY.git"
          git pull github ${GITHUB_REF} --ff-only
          /bin/sh scripts/csvDownload.sh OH https://coronavirus.ohio.gov/static/COVIDSummaryData.csv data/us-oh/oh-doh/raw
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
         pip install pandas
         pip install addfips
    - name: transform
      run: |
       python data/us-oh/oh-doh/harvester.py
       git add .
       git commit -m "adding OH data via github actions"
       git push github HEAD:${GITHUB_REF}
