name: statcan

on: 
  schedule:
#   #run daily at 6 UTC (2ET)
#   #note that this takes around 10 minutes to run so it should be the last one in the series
   - cron: '0 6 * * *'

# uncomment these lines if you need to run the pipeline manually. 
#   push:
   #run on every push to master
#     branches: [ master ]

jobs:
  
  ca-statcan:
   name: StatsCan Data Ingestion
   runs-on: ubuntu-latest
   steps:
    - uses: actions/checkout@v2
       #set up username and id 
    - uses: fregante/setup-git-token@v1
      with:
         token: ${{ secrets.GITHUB_TOKEN }}
    - name: pull data via curl
      run: /bin/sh scripts/statCanDownload.sh https://www150.statcan.gc.ca/n1/tbl/csv/13100766-eng.zip 13100766.csv data/ca/statcan/cases/raw/
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
         pip install pandas
    - name: transform
      run: |
       git remote add github "https://$GITHUB_ACTOR:$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY.git"
       git pull github ${GITHUB_REF} --ff-only
       python data/ca/statcan/cases/harvester.py
       git add .
       git commit -m "adding StatsCan data via github actions"
       git push github HEAD:${GITHUB_REF}
