name: statcan
#note that this is for the stats canada revised dataset. the original is no longer getting updated. 
on: 
  schedule:
   #run daily at 6 UTC (2ET)
   - cron: '0 6 * * *'

  workflow_dispatch:
     default:
        description: 'run manually'
        required: false

jobs:
  ca-statcan:
   name: StatsCan Data Ingestion
   runs-on: ubuntu-latest
   steps:
    - uses: actions/checkout@v2
       #set up username and id 
    - uses: fregante/setup-git-user@v1
    - name: pull data via curl
      run: |
       git remote add github "https://$GITHUB_ACTOR:$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY.git"
       git pull github ${GITHUB_REF} --ff-only
       apt-get update && apt-get install -y zip
       /bin/sh scripts/statCanDownload.sh https://www150.statcan.gc.ca/n1/tbl/csv/13100781-eng.zip 13100781.csv ./data/ca/statcan/cases_revised/raw/
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
         pip install pandas
    - name: transform
      run: |
       python data/ca/statcan/cases_revised/harvester.py
       git add .
       git commit -m "adding StatsCan Revised data via github actions"
       git push github HEAD:${GITHUB_REF}
    - name: Slack notification
      #should run if any previous step fails
      if: failure()
      env:
       SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
       SLACK_USERNAME: GitHub Actions # Optional. (defaults to webhook app)
       SLACK_CHANNEL: alerts-rds # Optional. (defaults to webhook)
       SLACK_AVATAR: repository # Optional. can be (repository, sender, an URL) (defaults to webhook app avatar)
      uses: Ilshidur/action-slack@master
      with:
          args: 'Something went wrong in the stats-can-revised workflow.' # Optional
