name: TN Education Data

on: 

   workflow_dispatch:
     default:
        description: 'run manually'
        required: false
   
   schedule:
   #run daily at 9:00 UTC / 5am eastern
     - cron: '00 9 * * *'

jobs:
 tn-doh:   
    name: TN-EDU Data Ingestion
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
       #set up username and id 
    - uses: fregante/setup-git-token@v1
      with:
         token: ${{ secrets.GITHUB_TOKEN }}
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas
        pip install addfips
        pip install xlsx2csv
    - name: transform
      run: |
       python data/us-tn/tn-edu/district-parser.py
       python data/us-tn/tn-edu/school-parser.py
       python data/us-tn/tn-edu/harvester_latest.py

       git add .
       git commit -m "adding TN Education data via github actions"
       git push github HEAD:${GITHUB_REF}
    - name: Slack notification
      #should run if any previous step fails
      if: failure()
      env:
       SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
       SLACK_USERNAME: GitHub Actions # Optional. (defaults to webhook app)
       SLACK_CHANNEL: alerts-rds # Optional. (defaults to webhook)
       SLACK_AVATAR: repository # Optional. can be (repository, sender, an URL) (defaults to webhook app avatar)
      uses: Ilshidur/action-slack@master
      with:
          args: 'Something went wrong in the TN-EDU workflow.' # Optional
